org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=2G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8
android.useAndroidX=true
# Tat incremental compile cua Kotlin -> tranh loi "different roots"
# (project o o D:, pub cache o o C: => Windows khong tinh duoc duong dan tuong doi giua 2 o dia)
kotlin.incremental=false
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
